### PR TITLE
Fix sample vite app

### PR DESCRIPTION
**Pull request by mainnet-pat**
address https://github.com/woodser/monero-ts/issues/229

### CODE REVIEW

**Comment by mainnet-pat** [comment]
https://node.sethforprivacy.com:18089 seems to have ssl issues, replaced with another node from monero.fail website

**Comment by mainnet-pat** [comment]
doing `npx vite dev` reveals yet another issue with `request` package 
image

**Comment by mainnet-pat** [comment]
Also while working on this I have seen that the `getFeeEstimate` calls threw because my regtest node did not return `fees` array in the result, just fee. Is this something unusual, because this field could be treated as optional in the response handling code

**Comment by woodser** [comment]
The sample code works in Firefox and gets most the way through in Brave, but fails on opening the wallet (`await walletRpc.openWallet("test_wallet_1", "supersecretpassword123");`):

image

Feels like we're very close if we can get past this last error (maybe again related to the request dependencies?).

**Comment by mainnet-pat** [comment]
I had this error. Which password do you use in monero-wallet-rpc command line?

**Comment by mainnet-pat** [comment]
I have used `supersecretpassword123`

**Comment by mainnet-pat** [comment]
I also see that auth headers are not set

**Comment by mainnet-pat** [comment]
So it works for me if I start `monero-wallet-rpc` with `--disable-rpc-login`.

Seems to be monero-ts or `request`-specific issue

**Comment by mainnet-pat** [comment]
Firefox-xhr: Found out that if I'd issue a single request to wallet rpc, it will return 401 with data related to auth like realm, etc. Upon second invocation of the same method, these data will be used to produce Authorization headers and xhr calls will succeed.
Fetch in other browsers simply does not work

**Comment by mainnet-pat** [comment]
It seems to me that digest auth is not implemented for `fetch` in `request`

**Comment by woodser** [comment]
> I had this error. Which password do you use in monero-wallet-rpc command line?

`--rpc-login rpc_user:abc123`, and the wallet's password is `supersecretpassword123`

**Comment by woodser** [comment]
> It seems to me that digest auth is not implemented for `fetch` in `request`

Yeah, the [HttpClient](https://github.com/woodser/monero-ts/blob/536ee4afedb3c8925f32a015efe304f1a58a957c/src/main/ts/common/HttpClient.ts#L94) uses fetch unless Firefox, then it uses digest auth via xhr.

**Comment by woodser** [comment]
> Also while working on this I have seen that the `getFeeEstimate` calls threw because my regtest node did not return `fees` array in the result, just fee. Is this something unusual? because this field could be treated as optional in the response handling code

The `fees` field is assumed to be initialied here: https://github.com/woodser/monero-ts/blob/536ee4afedb3c8925f32a015efe304f1a58a957c/src/main/ts/daemon/MoneroDaemonRpc.ts#L371

That could be made optional. Do you know if `result.quantization_mask` is missing as well? Could make that optional too if so.

**Comment by mainnet-pat** [comment]
> > Also while working on this I have seen that the `getFeeEstimate` calls threw because my regtest node did not return `fees` array in the result, just fee. Is this something unusual? because this field could be treated as optional in the response handling code
> 
> The `fees` field is assumed to be initialized here: https://github.com/woodser/monero-ts/blob/536ee4afedb3c8925f32a015efe304f1a58a957c/src/main/ts/daemon/MoneroDaemonRpc.ts#L371
> 
> That could be made optional. Do you know if `result.quantization_mask` is missing as well? Could make that optional too if so.

from the monero sources it seems that my regtest node's hardfork version did not reach the `HF_VERSION_2021_SCALING` which fills this vector:

```cpp
    const uint8_t version = m_core.get_blockchain_storage().get_current_hard_fork_version();
    if (version >= HF_VERSION_2021_SCALING)
    {
      m_core.get_blockchain_storage().get_dynamic_base_fee_estimate_2021_scaling(req.grace_blocks, res.fees);
      res.fee = res.fees[0];
    }
    else
    {
      res.fee = m_core.get_blockchain_storage().get_dynamic_base_fee_estimate(req.grace_blocks);
    }
    res.quantization_mask = Blockchain::get_fee_quantization_mask();
    res.status = CORE_RPC_STATUS_OK;
    return true;
```

the `quantization_mask` seems to be always present

**Comment by mainnet-pat** [comment]
Made use of new axios http client and fixed the vite dev env, so no need to do vite build which mangles the sources and makes harder to debug

https://github.com/mainnet-pat/xmr-sample-vite/commit/bcdcda27986cd0c2a8d98d94742cbcb11d9662b9

**Comment by woodser** [comment]
> from the monero sources it seems that my regtest node's hardfork version did not reach the HF_VERSION_2021_SCALING which fills this vector

Ok, so maybe it can be assumed that the `fees` field is present or else the daemon isn't set up right. Or we could make it tolerant.

> Made use of new axios http client and fixed the vite dev env, so no need to do vite build which mangles the sources and makes harder to debug
> 
> [mainnet-pat@bcdcda2](https://github.com/mainnet-pat/xmr-sample-vite/commit/bcdcda27986cd0c2a8d98d94742cbcb11d9662b9)

Great, please open any pull requests on the sample apps, and I can test this axios change in monero-ts and all the sample apps together.

**Comment by woodser** [comment]
> from the monero sources it seems that my regtest node's hardfork version did not reach the HF_VERSION_2021_SCALING which fills this vector:

Ok, thinking to make only the `fees` field optional then.

**Comment by mainnet-pat** [comment]
> > Made use of new axios http client and fixed the vite dev env, so no need to do vite build which mangles the sources and makes harder to debug
> > [mainnet-pat@bcdcda2](https://github.com/mainnet-pat/xmr-sample-vite/commit/bcdcda27986cd0c2a8d98d94742cbcb11d9662b9)
> 
> Great, please update this pull request, and I can test this axios change in monero-ts and all the sample apps together.

what should I update exactly?

**Comment by woodser** [comment]
I'm confused about your 2 PRs on this repo. Shouldn't it be one PR with all fixes to the vite app based on the axios change in monero-ts?

**Comment by mainnet-pat** [comment]
Right, I am also confused what you meant. How can I update your sample apps if you did not include new http client in monero-ts. Only with a pointer to my github repo like this: 
    "monero-ts": "https://github.com/mainnet-pat/monero-ts#563aa40af7357938d12a491ce56e520024b8bda0"

**Comment by mainnet-pat** [comment]
Apart from that, I have checked webpack and next sample apps with the test build from above. Both are working, I can create "preview" PRs against both repos for you to checkout and test locally

**Comment by woodser** [comment]
Yeah that line can be a placeholder in the PR for each sample app until the new monero-ts is released. My plan was to test the new monero-ts and each sample app (using the PR in each sample app repo, and manually installing the new version of monero-ts locally), then release a new version of monero-ts, and then the PR in each sample app repo can be updated.

But I'd expect there to only be one PR per sample app to test the changes to monero-ts, whereas this repo now has 2 PRs, so I'm not sure to apply which/both when testing against the new monero-ts repo.

**Comment by woodser** [comment]
> Apart from that, I have checked webpack and next sample apps with the test build with new HttpClient from above. Both are working, I can create "preview" PRs against both repos for you to checkout and test locally

Great yes, a single "preview" PR per sample app would be perfect, then I'll test all, release the new monero-ts, then we can update the sample app PRs.

**Comment by mainnet-pat** [comment]
Afterwards I can close both and make a new PR for new monero-ts version

**Comment by mainnet-pat** [comment]
closing in favor of #4

**Pull request closed without merging**
